# Generated by Django 4.2.2 on 2023-06-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videostreamApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
