# Generated by Django 4.2.2 on 2023-07-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostreamApp', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_1000',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos/1000'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_480',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos/480'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_720',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos/720'),
        ),
    ]
